Repository anushbhatia/Social-Scheduler, pull requests merged in 2020-08, with the labels that each got.

#13 Adding Illustartion from Undraw and basic form-@shawavisek35 done
  src/App.css
  src/components/Contact.jsx
  src/contact_illustration.svg
Labels: PR: unreviewed

#9 added text background image and social icons on about page.
  src/components/About.jsx
  src/components/assets/css/materialize.min.css
  src/components/assets/images/HakinCodes.png
  src/components/assets/images/about.svg
  src/components/assets/images/github.svg
  src/components/assets/images/instagram.svg
  src/components/assets/images/whatsapp.svg
  src/components/assets/js/materialize.js
  src/components/assets/js/materialize.min.js
  src/utils/screenSizes.js
Labels: PR: unreviewed

#15 Added formspree and form-validation to the updated code base (previous PR)
  src/components/Contact.jsx
Labels: CH-20, PR: unreviewed

#22 Sending email with Emailjs
  package-lock.json
  package.json
  src/lib/email.js
Labels: CH-20, PR: reviewed-approved, PR: unreviewed

#27 fix: typo in title
  public/index.html
Labels: PR: unreviewed

#26 Update LandingPage.jsx: major typo fix
  src/components/LandingPage.jsx
Labels: PR: unreviewed

#29 Created custom hook to fetch contributers data from the github API
  src/lib/contributers.js
Labels: CH-20, Easy, PR: reviewed-approved

#34 Cleared all console warnings related to linting and errors, fixes #31
  package-lock.json
  package.json
  public/index.html
  src/components/About.jsx
Labels: Beginner, CH-20, PR: reviewed-approved

#39 Home Page Navbar created and made responsive.
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/components/Navbar.jsx
  src/index.js
Labels: CH-20, Medium, enhancement

#36 Eslint
  .gitignore
  .idea/.gitignore
  .idea/Social-Scheduler.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  package-lock.json
  package.json
  src/App.js
Labels: CH-20, Easy, good first issue

#35 Added fillter for project owners and mentors
  public/_redirects
  src/data/adminList.js
  src/data/mentorList.js
  src/lib/contributers.js
Labels: CH-20, Easy, PR: reviewed-approved, PR: unreviewed, help wanted

#37 updated the detail issue #7 added a navbar link for contributor
  package-lock.json
  package.json
  src/App.js
  src/Detail.css
  src/components/Detail.js
  src/components/Footer.js
  src/components/Navbar.jsx
  src/components/assets/images/boyimage.png
  src/components/assets/images/girlimage.png
Labels: CH-20, Medium, PR: partially-approved, PR: unreviewed

#41 Minor formatting
  public/_redirects
  src/components/Contact.jsx
Labels: Beginner, CH-20, PR: reviewed-approved, PR: unreviewed, bug

#28 Home page issue#7 Footer
  public/index.html
  src/components/Detail.js
Labels: CH-20, Easy, PR: reviewed-changes-requested

#45 Fixing the eslint issues on the project
  package-lock.json
  package.json
Labels: PR: unreviewed

#60 admin and mentors details added
  .idea/workspace.xml
  src/components/Detail.js
Labels: PR: unreviewed

#63 Added Contact Us! form in footer
  src/App.js
  src/components/Footer.js
  src/components/UserRegistration.js
Labels: PR: unreviewed

#65 Added a custom 404 component for Default Page - @shankhanil007
  src/components/404-Page/Page_404.css
  src/components/404-Page/Page_404.jsx
  src/components/Default.jsx
Labels: PR: unreviewed
