Repository anushbhatia/Social-Scheduler, pull requests merged in 2020-10, with the labels that each got.

#92 Create header component
  src/App.css
  src/App.js
  src/components/assets/images/temp-logo.jpg
  src/components/layout/Navbar.jsx
Labels: CH-20, Medium, PR: merged, UI/UX

#91 Made proper indentation to most code and tidied unnecessary code. Wanna work on the header if i get permission.
  .prettierrc
  .vscode/settings.json
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/Detail.css
  src/components/About.jsx
  src/components/Contact.jsx
  src/components/Default.jsx
  src/components/LandingPage.jsx
  src/components/Signin.jsx
  src/components/UserRegistration.js
  src/components/layout/Footer.jsx
  src/components/layout/Navbar.jsx
  src/index.js
Labels: PR: unreviewed

#94 Update README.md
  README.md
Labels: PR: unreviewed

#95 changed the logo for hackincodes
  README.md
  logo.jpg
Labels: PR: unreviewed

#96 Create contribute.md
  contribute.md
Labels: PR: unreviewed

#97 Update contribute.md
  contribute.md
Labels: PR: unreviewed

#98 Update README.md
  README.md
Labels: PR: unreviewed

#99 Update README.md
  README.md
Labels: PR: unreviewed, hacktoberfest-accepted

#102 Removed Redundant NavLinks
  src/components/layout/Navbar.jsx
Labels: hacktoberfest-accepted
