Repository anushbhatia/Social-Scheduler, pull requests merged in 2020-09, with the labels that each got.

#61 added a authenticate route and added basic form page
  Temporary-Backend/.gitignore
  src/App.js
  src/components/Navbar.jsx
  src/components/Signin.jsx
  src/components/assets/images/google-icon.svg
  src/components/assets/images/undraw_Login.svg
Labels: CH-20, Medium, PR: reviewed-approved, PR: unreviewed, UI/UX

#71 fix: typo in Card.jsx and Detail.js
  src/components/Card.jsx
  src/components/Detail.js
Labels: Beginner, CH-20, bug

#74 chore: create PR and issues template.
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: reviewed-approved

#75 upd, fix: contributer's card.
  src/Detail.css
  src/components/Card.jsx
  src/lib/contributers.js
Labels: PR: unreviewed

#83 Links corrected
  Contribute.MD
Labels: Beginner, CH-20, PR: unreviewed, bug, documentation

#81 Fixed Wrong placeholder present in the sign-in page
  src/components/Signin.jsx
Labels: PR: unreviewed

#85 :star: refactor-contributors to single component
  src/App.js
  src/Detail.css
  src/components/Default.jsx
  src/components/Detail.js
  src/components/pages/404-Page/Page_404.css
  src/components/pages/404-Page/Page_404.jsx
  src/components/pages/Contributor/CardItem.jsx
  src/components/pages/Contributor/Cards.jsx
  src/data/mentorList.js
  src/lib/contributers.js
Labels: PR: unreviewed

#87 Bugs/console errors
  src/App.css
  src/App.js
  src/components/Footer.js
  src/components/layout/Footer.jsx
  src/components/layout/Navbar.jsx
  src/components/pages/404-Page/Page_404.jsx
  src/components/pages/Contributor/Cards.jsx
  src/lib/contributers.js
Labels: CH-20, Medium, PR: unreviewed

#88 GitHub action
  .github/auto_assign.yml
Labels: CH-20, Easy, PR: unreviewed

#89 Figma link added
  features.json
Labels: CH-20, Hard, PR: unreviewed, UI/UX
